### PR TITLE
🐛Not write response body for HEAD requests

### LINKED ISSUE #254: [BUG] Remediation should not be served for HEAD requests
**Describe the bug** 🐛

Remediation with body, such as Captcha, is served for Head requests. 

See https://github.com/golang/go/issues/66812 for details on similar case.

I can now see the details of why many remediation writes failed:

> INFO: CrowdsecBouncerTraefikPlugin: 2025/07/16 15:23:52 captcha:ServeHTTP captchaTemplateServe http2: request body closed due to handler exiting 

**Expected behavior** 👀

When a HEAD request is received, nothing is writen to the body.

### PR DESCRIPTION
**Pull request by david-garcia-garcia**
Fixes #254

This PR introduces two changes:

* Ban remediation body is not writen for HEAD requests
* For HEAD requests fallback to BAN instead of Captcha

Both with test coverage.

### CODE REVIEW

File: bouncer.go [hunk 1]
```diff
@@ -404,15 +404,21 @@ func handleBanServeHTTP(bouncer *Bouncer, rw http.ResponseWriter) {
...
+			bouncer.log.Info("handleBanServeHTTP could not write template to ResponseWriter: " + err.Error())
+		}
 	}
 }
 
 func handleRemediationServeHTTP(bouncer *Bouncer, remoteIP, remediation string, rw http.ResponseWriter, req *http.Request) {
 	bouncer.log.Debug(fmt.Sprintf("handleRemediationServeHTTP ip:%s remediation:%s", remoteIP, remediation))
-	if bouncer.captchaClient.Valid && remediation == cache.CaptchaValue {
+	// Only serve captcha for GET and POST requests, fallback to BAN for other methods. We need POST because the actual captcha post-processing is done in the POST request.
+	if bouncer.captchaClient.Valid && remediation == cache.CaptchaValue && (req.Method == http.MethodGet || req.Method == http.MethodPost) {
```
Comment (maxlerebourg) [inline bouncer.go:421]: Why you don't serve captcha page for PUT or DELETE ? Just do like for the ban page if not HEAD serve the captcha page ?

Comment (david-garcia-garcia) [reply bouncer.go]: In any case and to avoid further discussion and delays, I don't think this change has any relevant impact so I changed the code to only fallback to BAN for HEAD requests.

**Review by maxlerebourg — APPROVED** [review]
